# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

do_cell_fire_status <- function(fireyears, min_threshold, max_threshold, query_years, base_year, estimate_base_tsf, quiet = TRUE) {
    .Call(`_CERMBfiretools_do_cell_fire_status`, fireyears, min_threshold, max_threshold, query_years, base_year, estimate_base_tsf, quiet)
}

table_fire_status <- function(firehistory, veg, veg_thresholds, query_years, base_year, estimate_base_tsf, quiet = TRUE) {
    .Call(`_CERMBfiretools_table_fire_status`, firehistory, veg, veg_thresholds, query_years, base_year, estimate_base_tsf, quiet)
}

