# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

find_row <- function(x, col_index, value) {
    .Call(`_CERMBfiretools_find_row`, x, col_index, value)
}

mat_subset <- function(x, col_index, value) {
    .Call(`_CERMBfiretools_mat_subset`, x, col_index, value)
}

#' Determine fire status given interval thresholds and fire history
#'
#' This function determines the fire status of a location (e.g. point or
#' raster cell) given a vector of fire years, and the minimum and maximum
#' tolerable fire intervals (years) for the vegetation at the location.
#'
#' @param fireyears Vector of integer fire years. Any years beyond year_query
#'   are ignored, as are duplicate years.
#'
#' @param min_threshold Minimum tolerable fire interval (years).
#'
#' @param max_threshold Maximum tolerable fire interval (years).
#'
#' @param year_query Reference year for the analysis.
#'
#' @param year_base Year taken as the start of the data period.
#'
#' @param quiet If true (default) do not print debugging output.
#'
#' @return An integer code for fire status.
#'
#'
#' @export
cell_fire_status <- function(fireyears, min_threshold, max_threshold, year_query, year_base, quiet = TRUE) {
    .Call(`_CERMBfiretools_cell_fire_status`, fireyears, min_threshold, max_threshold, year_query, year_base, quiet)
}

#' Determine fire status for a set of locations
#'
#' @export
table_fire_status <- function(cell_firehistory, cell_veg, veg_thresholds, year_query, year_base, quiet = TRUE) {
    .Call(`_CERMBfiretools_table_fire_status`, cell_firehistory, cell_veg, veg_thresholds, year_query, year_base, quiet)
}

